# Generated by Django 4.1.3 on 2022-11-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='contact')),
                ('banner_title', models.CharField(max_length=100)),
                ('info_text', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=150)),
                ('dial_number', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=30)),
                ('start_time', models.TimeField(auto_now=True)),
                ('end_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=14)),
                ('subject', models.CharField(max_length=70)),
                ('message', models.TextField(max_length=250)),
            ],
        ),
    ]
