# Generated by Django 4.1.3 on 2022-12-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_faq_alter_sitecontact_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('payment', 'payment'), ('shipping', 'shipping'), ('order_and_return', 'order_and_return')], default='payment', max_length=100),
        ),
    ]
