# Generated by Django 4.1.7 on 2023-02-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0003_faq_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutEshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('heading_span', models.CharField(max_length=100)),
                ('vision_tittle', models.CharField(max_length=150)),
                ('vision_description', models.CharField(max_length=1000)),
                ('mission_tittle', models.CharField(max_length=150)),
                ('mission_description', models.CharField(max_length=1000)),
                ('shop_heading', models.CharField(max_length=150)),
                ('shop_caption', models.CharField(max_length=250)),
                ('shop_description', models.CharField(max_length=1000)),
                ('about_img1', models.ImageField(upload_to='about_eshop')),
                ('about_img2', models.ImageField(upload_to='about_eshop')),
                ('about_banner', models.ImageField(upload_to='about_eshop')),
                ('brands_text', models.CharField(max_length=250)),
                ('brands_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
